/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomNavBar: typeof import('./src/components/custom-nav-bar/custom-nav-bar.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
  }
}
